### PR TITLE
Updating values in config template for managed-upgrade-operator

### PR DESCRIPTION
**Pull request by ravitri**
This PR is to reflect the changes in osde2e repository based on following two PRs:
- https://github.com/openshift/managed-cluster-config/pull/498
- https://github.com/openshift/managed-cluster-config/pull/497

Subsequent changes to be reflected in osde2e flow based on review of above two PRs can be made part of this PR once it's approved and merged.

cc: @sedroche @mrbarge

### CODE REVIEW

**Comment by ravitri** [comment]
/hold 

Keeping on hold till the mentioned two PRs are merged

**Comment by ravitri** [comment]
Based on https://github.com/openshift/managed-cluster-config/pull/498 PR, adding workerNodeTime field again temporarily. This would be removed in future.

**Comment by mrbarge** [comment]
This looks good to me. @jeefy we need this merged in order for upgrades in staging (and soon, production) to continue working with the next release of the managed-upgrade-operator. Would you be able to give this one some :eyes: today if you have capacity? Thank you in advance!

(We're going to have a few more PRs like these in the coming week as we iterate pretty fast with some new managed-upgrade-operator releases - I apologise in advance..)

**Comment by jeefy** [comment]
Absolutely. I just made changes to `pkged.go` so once that's rebased I can lgtm it.
/approve

**Comment by ravitri** [comment]
@jeefy - Thanks a lot! I have pushed the rebase commit.. Could you validate and add LGTM when convenient?

**Pull request merged**
