### PR TITLE
Clean up security groups orphaned by AWS LB deletion test

### PR DESCRIPTION
**Pull request by abyrne55**
The test added in #985 ([OSD-8474](https://issues.redhat.com/browse/OSD-8474)) covering load balancer deletion doesn't currently clean up the security groups left over from deleted load balancers, causing them to become "orphaned" and pile up over time. This PR fixes this bug by recording which security groups are associated with a load balancer pre-deletion, removing any references to said groups (required by AWS in order to delete group), and then deleting these orphan security groups post-LB-recreation.

This PR addresses [OSD-11485](https://issues.redhat.com/browse/OSD-11485), where it was noticed that this bug was causing us to rub up against [AWS's limits](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups) on security group quantity.

**Steps to Test**
1. Create a CCS OSD stage cluster, then observe total number of security groups reported by AWS EC2 management console.
2. Run this test: `./out/osde2e test --cluster-id $CLUSTER_ID --skip-health-check --configs "stage" --focus-tests "rh-api-lb-test"`
3. Confirm the test reports "Deleted orphaned security group sg-XYZ"
4. Confirm that total number of security groups reported by AWS EC2 management console hasn't grown since step 1 (i.e., ensure no orphan security groups remain)

### CODE REVIEW

**Comment by MrSantamaria** [comment]
@abyrne55 The last failure had to do with the ELB test. Rerunning again.

**Comment by abyrne55** [comment]
/retest

> haven't seen this ELB test fail in the last few runs though

So I may have spoken too soon 😅 

The test failed this last run with the following output:
```
[restful] 2022/07/14 19:37:25 log.go:30: Old LB name a30a43c135d8a4825a300b9b9f824f8d 
[restful] 2022/07/14 19:37:25 log.go:30: Old LB deleted
[restful] 2022/07/14 19:37:25 log.go:30: Looking for new LB
[restful] 2022/07/14 19:37:25 log.go:30: rh-api service not deleted yet
[restful] 2022/07/14 19:37:40 log.go:30: Looking for new LB
[restful] 2022/07/14 19:37:40 log.go:30: rh-api service not deleted yet
<previous 2 lines repeat 18 times>
[restful] 2022/07/14 19:42:10 log.go:30: rh-api service not deleted yet
[restful] 2022/07/14 19:42:25 log.go:30: Looking for new LB
[restful] 2022/07/14 19:42:25 log.go:30: rh-api service not deleted yet
[restful] 2022/07/14 19:42:25 log.go:30: Looking for new LB
[restful] 2022/07/14 19:42:25 log.go:30: rh-api service not deleted yet
------------------------------
• [FAILED] [600.001 seconds]
[Suite: operators] CloudIngressOperator rh-api-lb-test [It] manually deleted LB should be recreated in AWS
/go/src/github.com/openshift/osde2e/pkg/common/util/util.go:43
  Unexpected error:
      <*errors.errorString | 0xc0000ad4d0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred
  In [It] at: /go/src/github.com/openshift/osde2e/pkg/e2e/operators/cloudingress/rhapi_lb.go:195
------------------------------
```
Looks like the test failed because either EC2 didn't fully delete the load balancer quickly enough, or because K8s failed to recognize that the LB had been deleted. Either way, it doesn't look like any of the code substantially touched by this PR was even executed before the timeout. I've trigger the re-test once more; maybe we'll get lucky this time 🤞🏻

**Pull request merged**
