### PR TITLE
e2e/verify: wait for deployment to be created

### PR DESCRIPTION
**Pull request by jbpratt**
the test keeps failing because the deployment isn't created yet but it gets created within 30 seconds of the test failing. Let's wait for it to exist and retry the GET request as it should _eventually_ succeed.

Signed-off-by: Brady Pratt <bpratt@redhat.com>

### CODE REVIEW

**Comment by MrSantamaria** [comment]
lgtm but I'm confused on one aspect. When removing the 3 minute timeout what becomes the timeout? 
I believe the wait package has a 2 min default timeout,  and the eventually is every second(I think) 
So is this just checking every second for the default 2 minutes?

**Comment by jbpratt** [comment]
> lgtm but I'm confused on one aspect. When removing the 3 minute timeout what becomes the timeout? I believe the wait package has a 2 min default timeout, and the eventually is every second(I think) So is this just checking every second for the default 2 minutes?

I'm just falling back to the default timeouts https://github.com/kubernetes-sigs/e2e-framework/blob/main/klient/wait/wait.go#L25-L28

We have a big problem of setting timeouts all over the place without rhyme or reason so I'm just trying to minimize the arbitrary timeouts

**Comment by MrSantamaria** [comment]
> I'm just falling back to the default timeouts https://github.com/kubernetes-sigs/e2e-framework/blob/main/klient/wait/wait.go#L25-L28
>
Oh it is 5 minutes, so it is an increase. 

> We have a big problem of setting timeouts all over the place without rhyme or reason so I'm just trying to minimize the arbitrary timeouts
> 

I wouldn't consider the different timeouts a problem. 
Personally I would say that the root cause for scattered timeouts are a lack of defined SLOs per test. 
That would be a great place for QE to define timeout strategies across Openshift. For a test like this it starts with giving it an actual owner. 

This would be a great topic of discussion for our standup. 
In the interim lgtm! Thanks for the explanation.

**Pull request merged**
