### PR TITLE
SDCICD-173. Gate report generation.

### PR DESCRIPTION
**Pull request by meowfaceman**
Gating reports for the gating of OCP releases are now generated. This
will allow us to regularly compute gating reports and analyze them in
follow up jobs.

### CODE REVIEW

**Comment by meowfaceman** [comment]
/hold
Want to discuss this some, so I'm going to hold it for now.

**Comment by meowfaceman** [comment]
Some example output:
```
➜  osde2e git:(SDCICD-173) osde2e gate int openshift-v4.4.0
2020/03/03 13:13:57 Updating the osde2e binary.
2020/03/03 13:13:58 Generated temporary directory /tmp/osde2e916204621 for field ReportDir
2020/03/03 13:13:58 Generated random string hwa for field Suffix
{
  "viable": false,
  "versions": [
    "openshift-v4.4.0-0.nightly-2020-03-03-002753",
    "openshift-v4.4.0-0.nightly-2020-03-03-033819"
  ],
  "failingTests": [
    "[install] [Suite: e2e] Cluster state should be captured with must-gather",
    "[install] [Suite: operators] [OSD] Upgrade Configure AlertManager Operator Operator Upgrade should upgrade from the replaced version",
    "[install] [Suite: operators] [OSD] Upgrade RBAC Permissions Operator Operator Upgrade should upgrade from the replaced version"
  ]
}
➜  osde2e git:(SDCICD-173) osde2e gate stage openshift-v4.3.0
2020/03/03 13:14:30 Updating the osde2e binary.
2020/03/03 13:14:31 Generated temporary directory /tmp/osde2e606548033 for field ReportDir
2020/03/03 13:14:31 Generated random string gea for field Suffix
{
  "viable": true,
  "versions": []
}

➜  osde2e git:(SDCICD-173) osde2e gate prod openshift-v4.3.0
2020/03/03 13:13:45 Updating the osde2e binary.
2020/03/03 13:13:45 Generated temporary directory /tmp/osde2e922056249 for field ReportDir
2020/03/03 13:13:45 Generated random string ou0 for field Suffix
{
  "viable": false,
  "versions": [
    "openshift-v4.3.0"
  ],
  "failingTests": [
    "[install] [Suite: scale-nodes-and-pods] Scaling should be tested with PodVertical",
    "[install] [Suite: operators] [OSD] Certman Operator certificate secret should be applied when cluster installed certificate secret exist under openshift-config namespace",
    "[install] [Suite: operators] [OSD] Certman Operator certificate secret should be applied when cluster installed certificate secret should be applied to apiserver object",
    "[install] [Suite: scale-nodes-and-pods] Scaling should be tested with NodeVertical"
  ]
}
```

**Comment by jeefy** [comment]
Definitely a good direction. 

/lgtm

**Pull request merged**
