### PR TITLE
add ds/rs check for cluster health check

### PR DESCRIPTION
**Pull request by bmeng**
add the ds rs replica count check as part of the cluster health check

the managed upgrade will also be able to consume this

### CODE REVIEW

**Comment by bmeng** [comment]
cc @mrbarge

**Comment by whereswaldon** [comment]
@bmeng Does this supercede #840 ?

**Comment by bmeng** [comment]
@whereswaldon ah, yes, this is going to address the last comment in #840 
I will close that one once this merged.

**Comment by bmeng** [comment]
tested this on a local staging cluster. it works well

**Pull request merged**
