### PR TITLE
OSD-8474 (Squashed) Added LB test for GCP

### PR DESCRIPTION
**Pull request by ritmun**
Squashed PR for https://github.com/openshift/osde2e/pull/1052 

/cc @MrSantamaria @mbarnes

### CODE REVIEW

**Comment by ritmun** [comment]
retest

**Comment by MrSantamaria** [comment]
Making changes to Pr-Check:
https://github.com/openshift/release/pull/27263

**Comment by MrSantamaria** [comment]
Closing this PR and instead will continue here:
https://github.com/openshift/osde2e/pull/1078

**Pull request closed without merging**
