### PR TITLE
SDCICD-113. Get Hive logs after each test.

### PR DESCRIPTION
**Pull request by meowfaceman**
We now get Hive logs after each test.

### CODE REVIEW

**Comment by meowfaceman** [comment]
One thing I want to note here is that the behavior is a little strange:

```
2019/12/18 14:39:54 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:54 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:55 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:55 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:57 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:58 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:58 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:39:59 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:40:00 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:40:00 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
•2019/12/18 14:40:02 Getting logs for cluster '1a41erqovfjcs4m4uc0gq6faftlhprh7'...
```
It still seems to behave properly, but I couldn't tell you why this is happening.

**Comment by meowfaceman** [comment]
/hold
Trying something. I may have figured this out.

**Comment by meowfaceman** [comment]
/hold cancel
Looks like this was behaving properly, it's just that ginkgo is quiet about tests which execute in a short time frame. I've quieted down the log collection aftereach method.

**Comment by jeefy** [comment]
/lgtm

:tada:

**Pull request merged**
