### PR TITLE
SDCICD-250. Condense configs, switch to Viper.

### PR DESCRIPTION
**Pull request by meowfaceman**
The config object has largely been ripped out and replaced with Viper.
This allows us to disregard our own custom rolled config logic and
additionally allows providers to specify and load their own configs.

### CODE REVIEW

**Comment by jeefy** [comment]
/lgtm

This cleans up a LOT of code and I am here for this.

**Comment by meowfaceman** [comment]
/hold cancel

Got most of the way through an upgrade (ran into the openshift-samples) but, but otherwise everything seems to have gotten through, so I'm going to call this good.

**Comment by jeefy** [comment]
/lgtm

:pray:

**Pull request merged**
