### PR TITLE
Port osde2e CLI to cobra

### PR DESCRIPTION
**Pull request by mrbarge**
**About**
This PR provides a port of osde2e's CLI interface to [cobra](https://github.com/spf13/cobra).

cobra is a subcommand-driven library similar to the existing [subcommand](https://github.com/google/subcommands) library used by osde2e.

**Rationale**
Its adoption brings a number of potential benefits:
- conformance with other OSD-related tools (kubectl, OCM and openshift-tests all use cobra) both for ease-of-development purposes and for producing a common usability interface.
- easy bash completion 
- dynamic tab-completion 
I thought these might be slightly useful in making the CLI interface a little more usable, and might be a useful base for allowing any future ideas or improvements.

**Issues**
I believe this PR is _almost_ entirely a drop-in replacement for the existing osde2e (meaning that existing means of running osde2e will work with the port), with one exception: the flags require a double-dash instead of a single-dash.

That is to say:
`osde2e test -configs=e2e-suite -custom-configs=blah`
is invalid, and should instead be:
`osde2e test --configs=e2e-suite --custom-configs=blah`

I have addressed areas of the Makefile where this is a problem.

**Bash completion**
The main feature added is bash completion and dynamic flag argument completion.

_Source the generated bash completion_
`. <(osde2e completion)`

_Tab complete configs, output formats, etc_
`osde2e test --configs=<tab><tab>`
`addon-suite    int   prod     two-releases-from-prod-default ...`

### CODE REVIEW

**Comment by meowfaceman** [comment]
/approve

This is so awesome. Very well timed -- was literally just thinking about doing this as well!

**Comment by mrbarge** [comment]
Thanks @meowfaceman ! I've made a couple of additional small fixes, but otherwise the branch should be good to go now. Very excited about #400 too - I _think_ these PRs will play nicely together without too much trouble. But I'm happy to hold off until #400 is merged, and then work on whatever's needed afterwards to get this up and running - please do whatever works best for you and the team. :)

**Comment by meowfaceman** [comment]
I'm fine with either one going in first. However it shakes out is fine with me. :-)

**Comment by jeefy** [comment]
/lgtm

Leaving the hold here till #400 is in

**Comment by jeefy** [comment]
@mrbarge Figured that might happen. Once the gomod conflicts are resolved we can get this in. :)

**Pull request merged**
