### PR TITLE
fix common/runner importing random log package

### PR DESCRIPTION
**Pull request by jbpratt**
Signed-off-by: Brady Pratt <bpratt@redhat.com>

### CODE REVIEW

**Comment by MrSantamaria** [comment]
@jbpratt could you give me more of a description here? 
I'm not sure why go-restful was pulled for logs.

**Comment by MrSantamaria** [comment]
Initial PR:
https://github.com/openshift/osde2e/pull/345

I'm not fully sure what this had to do with the addon suite but I'm not sure we need to make this swap right now.

**Comment by jbpratt** [comment]
> @jbpratt could you give me more of a description here? I'm not sure why go-restful was pulled for logs.

it looks like it was just a mistake from goimports or something when the initial PR was made https://github.com/openshift/osde2e/blob/2de8798c7cb98c303eee60fb02815b4343ab1916/pkg/common/runner/service.go#L104

**Comment by jbpratt** [comment]
> Initial PR: #345
> 
> I'm not fully sure what this had to do with the addon suite but I'm not sure we need to make this swap right now.

updated the commit message with more details, it is just a simple mistake of importing the wrong package, there is no functionality that package is providing that we need directly

**Comment by MrSantamaria** [comment]
Huh that is interesting. Looking at my local branch it got pulled into the cloudingress operator test. 
Can't say I see a conflict though, this does seem random.

**Pull request merged**
