### PR TITLE
Onboard addon operator healthcheck

### PR DESCRIPTION
**Pull request by thetechnick**
Part of on-boarding the Addon Operator to OSD, to get the discussion going.

Note that I also added the controller-runtime client to work typed with the AddonOperator object and use the apimachinery condition helpers, otherwise I would have to do a lot of type-casting with the dynamic client.

Warning: This PR should not be merged till the Addon Operator is actually deployed as part of OSD.

### CODE REVIEW

**Comment by cblecker** [comment]
@thetechnick You might want to have a look at the operators pattern in this directory: https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/configurealertmanager.go

There's a bunch of helper functions to test various aspects of an operator and it's installation.

**Comment by MrSantamaria** [comment]
@thetechnick This PR hasn't received updates in a while. Can we close this?

**Comment by MrSantamaria** [comment]
Closing this as I didn't get an update in a week. Please reopen if needed.

**Pull request closed without merging**
