### PR TITLE
e2e/webhooks: refactor Managed Cluster Validating Webhooks tests

### PR DESCRIPTION
**Pull request by jbpratt**
Refactor the Managed Cluster Validating Webhooks tests as a proof of
concept for applying a consistent set of standards, heavily utilizing
Ginkgo, Gomega, and the e2e-framework, to each test to increase
maintainability and ease the process of expanding feature coverage by
better understanding what currently exists. This consolidates each
tested webhook into a single suite, covering the following webhooks:

- pod
- regularuser
- techpreviewnoupgrade
- hiveownership
- scc (new)
- namespace
- prometheusrule

and install tests. Two webhooks are not covered, `clusterlogging` which
is not deployed to >4.6 clusters ~~and `prometheusrule` which currently
has tests in development.~~

Many tests use varying level of Ginkgo functionality like
`BeforeEach`/`AfterEach`, some falling back to `defer` or varying
methods of creating and waiting for resources rather than a consistent
set of standard helpers/layout. While each test is different, a common
pattern can be devised to provide consistentcy across the tests. Having
this common pattern applied across tests makes it easy to work with
existing tests and add new tests.

Test case naming has been improved to provide a readable description of
the test. `Describe` and nested `It` clauses are combined to build the
name of the test used in the final report which can lead to poorly named
tests if the author is not aware. More information on test naming can
come from sig-testing's [document on writing good e2e
tests](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md).

Within the tests, the kubernetes-sigs/e2e-framework is proposed to be
used for interacting with the cluster. It provides a client ("klient")
exposing a controller runtime client that schemas can be registered
with, allowing us to dynamically interact with objects using similar
crud operations. On top of the client, there are many helpers developed
that meet many of the needs within the tests. This allows osde2e to be
focused more on Ginkgo and a thin layer of test helpers. Opportunities
can be taken to contribute functionality developed back to the
e2e-framework.

A handful of tests have been removed due to being duplicated or
consolidated into a single test such as the install tests. A few new
tests have been added to cover missing features/branches within the
webhooks such as the SCC test to validate modifications made.

Signed-off-by: Brady Pratt <bpratt@redhat.com>
Co-authored-by: Ryan Williams <3375653+ryankwilliams@users.noreply.github.com>

for a list of tests added and removed:

<details>

before (24):

```
[Suite: service-definition] [OSD] NodeLabels Modifying nodeLabels is not allowed node-label cannot be added
[Suite: service-definition] [OSD] regularuser validating webhook regularuser validating webhook Privledged users allowed to create autoscalers and delete clusterversion objects
[Suite: informing] [OSD] techpreviewnoupgrade blocking webhook techpreviewnoupgrade webhook Webhook will block UPDATE requests if TechPreviewNoUpgrade feature set exists in FeatureGate
[Suite: informing] [OSD] pod validating webhook worker nodes on worker nodes
[Suite: informing] [OSD] pod validating webhook pod webhook Verify the validation webhook service is running
[Suite: informing] [OSD] pod validating webhook pod webhook Test 1: Webhook will mark pod spec invalid and block deploying
[Suite: informing] [OSD] pod validating webhook pod webhook Test 2: Webhook will mark pod spec invalid and block deploying
[Suite: informing] [OSD] pod validating webhook pod webhook Webhook will allow pod to deploy
[Suite: informing] [OSD] pod validating webhook pod webhook Webhook will allow pod to deploy (should be disallow)
[Suite: informing] [OSD] pod validating webhook pod webhook RBAC will deny deploying pod
[Suite: informing] [OSD] pod validating webhook pod webhook RBAC will deny deploying pod (duplicated test)
[Suite: informing] [OSD] hive ownership validating webhook hiveownership validating webhook dedicated admins cannot delete managed CRQs
[Suite: informing] [OSD] hive ownership validating webhook hiveownership validating webhook a random user cannot delete managed CRQs
[Suite: informing] [OSD] hive ownership validating webhook hiveownership validating webhook Members of SRE can update a managed quota object
[Suite: informing] [OSD] hive ownership validating webhook hiveownership validating webhook as dedicated admin can update crqs inside the cluster that are non managed.
[Suite: informing] [OSD] hive ownership validating webhook hiveownership validating webhook as dedicated admin can create a crq inside the cluster that is non managed.
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook dedicated admins cannot manage privileged namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Non-privileged users cannot manage privileged namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Privileged users can manage all namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Non-privileged users can manage all non-privileged namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook dedicated admin can not create PrometheusRule
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Non-privileged users cannot create prometheusrule in privileged namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Privileged users can create prometheusrule in all namespaces
[Suite: e2e] [OSD] namespace validating webhook namespace validating webhook Non-privileged users can create prometheusrule all non-privileged namespaces
[Suite: e2e] Validation Webhook should exist and be running in the cluster
```

after (20):

```
Managed Cluster Validating Webhooks exists and is running [E2E, ROSA, CCS, STS, AWS, GCP, Azure, Install]
Managed Cluster Validating Webhooks sre-pod-validation blocks pods scheduled onto master/infra nodes [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-pod-validation allows cluster-admin to schedule pods onto master/infra nodes [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-techpreviewnoupgrade-validation blocks customers from setting TechPreviewNoUpgrade feature gate [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-regular-user-validation blocks unauthenticated users from managing "managed" resources [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-regular-user-validation allows privileged users to manage "managed" resources system:* [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-regular-user-validation allows privileged users to manage "managed" resources backplane-cluster-admin [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-regular-user-validation only blocks configmap/user-ca-bundle changes [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-regular-user-validation blocks modifications to nodes [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-hiveownership-validation blocks deletion of managed ClusterResourceQuotas [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-hiveownership-validation allows a member of SRE to update managed ClusterResourceQuotas [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-hiveownership-validation allows dedicated-admins can manage unmanaged ClusterResourceQuotas [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-scc-validation blocks modifications to default SecurityContextConstraints [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-namespace-validation blocks dedicated admins from managing privileged namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-namespace-validation block non privileged users from managing privileged namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-namespace-validation allows privileged users to manage all namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-namespace-validation allows non privileged users to manage non privileged namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-prometheusrule-validation blocks users from creating PrometheusRules in privileged namespaces as dedicated-admin [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-prometheusrule-validation blocks users from creating PrometheusRules in privileged namespaces as random user [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-prometheusrule-validation allows backplane-cluster-admin to manage PrometheusRules in all namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
Managed Cluster Validating Webhooks sre-prometheusrule-validation allows non privileged users to manage PrometheusRules in non privileged namespaces [E2E, ROSA, CCS, STS, AWS, GCP, Azure]
```

</details>

[SDCICD-864](https://issues.redhat.com//browse/SDCICD-864)

/hold

### CODE REVIEW

**Comment by jbpratt** [comment]
marked as hold as there are still a few things we need to fix up before I'm ready to merge this but it this is ready for a review!

/assign @mrbarge @ritmun @MrSantamaria @ryankwilliams

**Comment by mrbarge** [comment]
Gave this a read-through - I was more curious to sanity check the ongoing relevancy of any of these tests, but I think they are all still fine and valid to keep checking. It all looks good to me, thanks!

**Comment by MrSantamaria** [comment]
lgtm
A few comments: 

1. Based on the Sig's testing guidelines do we want to enforce the assertion fail logs? I noticed some aren't added but that could be part of another PR. 
2. I'm not married to the naming conventions but on the configs/e2e-suite.yaml "- 'Managed Cluster Validating Webhooks'" to something like [Suite: Webhooks] or do we want to be more verbose with the rest of the suites?
3. Should we declare the manifests outside the describe call and just pass them by reference? That's just a readability for me with the test. 
4. Should we move some of those functions deleteNamespace, createNamespace, etc... to higher directories for all the operators to leverage?

**Comment by MrSantamaria** [comment]
In reference to the other Ryan opened the test that got merged into one file would lose the service-role definition. I'm not sure if that's important tbh.

**Comment by jbpratt** [comment]
> lgtm A few comments:
> 
>     1. Based on the Sig's testing guidelines do we want to enforce the assertion fail logs? I noticed some aren't added but that could be part of another PR.

Its possible we should, I've been a bit hesitant to over apply but it should probably be looked it. I would prefer the proper assertion fail log over verbose logging around the functions.

> 
>     2. I'm not married to the naming conventions but on the configs/e2e-suite.yaml "- 'Managed Cluster Validating Webhooks'" to something like [Suite: Webhooks] or do we want to be more verbose with the rest of the suites?
> 

We want the suite names to be tied to what it is, not including information like `[Suite: X]` anymore as it just clutters the output of a test name. It would be great if we could move towards being more verbose all around (a lot of our logic around this is reading end test case names within testgrid)

>     3. Should we declare the manifests outside the describe blocks and just pass them by reference? That's just for readability for me with the test.
> 
>     4. Should we move some of those functions deleteNamespace, createNamespace, etc... to higher directories for all the operators to leverage?

I wanted to start with specific helpers in the place they are needed and try to generalize from there. My fear about bumping a deleteX or createX to a higher level is it being misused/generalized to a point of complexity. The helpers right now are very simple and it would be nice to keep it that way. My example of the `deleteNamespace` actually already exists within the operators but it was copy pasted poorly (https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/dvo.go#L157) mentioned namespace validating webhook :smile: 

I think the approach with helpers should be something proven as reusable and applicable in multiple places (like the `asX` helpers that _do_ need to be moved to a higher level for all tests to utilize) 

@MrSantamaria thanks for the ocmments!

**Comment by jbpratt** [comment]
> 

thanks for catching this! When reviewing that test, I stripped it out and moved it to the regularuser webhook -> `Managed Cluster Validating Webhooks sre-regular-user-validation blocks modifications to nodes [E2E, ROSA, CCS, STS, AWS, GCP, Azure]` as it was doing exactly what I needed

**Comment by MrSantamaria** [comment]
> I  wanted to start with specific helpers in the place they are needed and try to generalize from there. My fear about bumping a deleteX or createX to a higher level is it being misused/generalized to a point of complexity. The helpers right now are very simple and it would be nice to keep it that way. My example of the deleteNamespace actually already exists within the operators but it was copy pasted poorly (https://github.com/openshift/osde2e/blob/main/pkg/e2e/operators/dvo.go#L157) mentioned namespace validating webhook 😄

This is really smart! I should have done this instead of writing comments everywhere! Thanks for all the answers.

**Comment by MrSantamaria** [comment]
The impersonate package is nice! 
/lgtm

**Pull request merged**
