### PR TITLE
Disable addon list on scale tests

### PR DESCRIPTION
**Pull request by agopala95**
Inserted a config flag check to disable listing of addons in clusters for a scale test during health check polling.

### CODE REVIEW

**Review by jeefy — CHANGES_REQUESTED** [review]
There's another instance of listing addons that was missed: https://github.com/openshift/osde2e/blob/main/pkg/common/providers/ocmprovider/cluster.go#L753-L771

This is on me, but I think a better approach now would be to add a completely separate config option/env var (`SKIP_ADDON_LIST`? I'm open to somethign different) and then check the config option instead of introspecting the cluster properties.

**Comment by agopala95** [comment]
> There's another instance of listing addons that was missed: https://github.com/openshift/osde2e/blob/main/pkg/common/providers/ocmprovider/cluster.go#L753-L771
> 
> This is on me, but I think a better approach now would be to add a completely separate config option/env var (`SKIP_ADDON_LIST`? I'm open to somethign different) and then check the config option instead of introspecting the cluster properties.

I've made use of the env var/config option. Thanks for the tip.

**Review by whereswaldon — APPROVED** [review]

**Pull request merged**
