### PR TITLE
check managed-velero-operator and velero are deployed to infra node

### PR DESCRIPTION
**Pull request by NautiluX**

### CODE REVIEW

**Comment by NautiluX** [comment]
/hold
this needs to wait for https://github.com/openshift/managed-velero-operator/pull/30 and https://github.com/openshift/managed-cluster-config/pull/177

**Comment by jeefy** [comment]
/assign

For when it's unheld.

**Comment by meowfaceman** [comment]
@NautiluX I notice the dependent PRs have been merged -- can we unhold this?

**Comment by NautiluX** [comment]
Unfortunately not. The test currently fails, as the pod, when the cluster is newly created get scheduled to non-infra nodes because of the node affinity `preferredDuringSchedulingIgnoredDuringExecution` currently trying to figure out a good way to mitigate this.

**Pull request closed without merging**
