### PR TITLE
[OSD-11101] add testing for remove proxy

### PR DESCRIPTION
**Pull request by bmeng**
To close [OSD-11101](https://issues.redhat.com//browse/OSD-11101)

Tested locally with following

```
osde2e test --configs proxy-suite --kube-config $KUBECONFIG -e stage --skip-health-check
```

It will run the adding proxy firstly, and then run the removing proxy. Both succeeded.

### CODE REVIEW

**Comment by MrSantamaria** [comment]
@bmeng few questions. 
I just talked to Matt recently on this effort, and just wondering was this tested with a proxy that was already set up?

**Comment by bmeng** [comment]
Hi @MrSantamaria 
yes, this needs the proxy to be setup before testing.
It likes the add proxy testing, but in reverse.

**Comment by mrbarge** [comment]
Tested this successfully.
/lgtm

**Pull request merged**
